// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ylozddeatmlahklpldww.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlsb3pkZGVhdG1sYWhrbHBsZHd3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3MTkxNjEsImV4cCI6MjA1ODI5NTE2MX0.pevbBuQuM0cGgCOmAbYUMTLG3I2bitmIMkfD2Ac7WkM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);